[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tdevice.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]
runner = '/home/craigjb/Projects/probe-rs/target/release/probe-rs run --chip-description-path vexriscv.yaml --chip=vexriscv'

[build]
target = "riscv32imc-unknown-none-elf"

[alias]
rr = "run --release"
br = "build --release"
