[target.riscv32i-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]
runner = 'probe-rs run --chip-description-path vexriscv.yaml --chip=vexriscv'

[build]
target = "riscv32i-unknown-none-elf"

[alias]
rr = "run --release"
br = "build --release"
