[tasks.svd-clean]
script = [
  "rm -rf src",
  "rm -f build.rs",
  "rm -rf svdout",
]

[tasks.svd-generate]
script = [
  "mkdir -p svdout",
  "svd2rust --target riscv -i slabware.svd -o svdout",
  "form -i svdout/lib.rs -o src/",
  "cp svdout/build.rs build.rs",
  "cargo fmt"
]

[tasks.svd]
run_task = [
    { name = ["svd-clean", "svd-generate"] },
]
