[default.probe]
protocol = "Jtag"

[default.general]
chip = "VexRiscv"
chip_descriptions = ["vexriscv.yaml"]

[default.rtt]
enabled = true
up_channels = [
    { channel = 0, mode = "NoBlockSkip", format = "Defmt", show_location = true },
]
