//         DO NOT EDIT MANUALLY
// THIS FILE IS AUTO-GENERATED BY FUSE-ZYNQ

package zynqps;

import spinal.core._
import spinal.lib._
import spinal.lib.bus.amba4.axi._

object ZynqPs {
  val mAxiGpConfig = Axi4Config(
    addressWidth = 32,
    dataWidth = 32,
    useId = true,
    idWidth = 12,
    useRegion = false,
  )
}

class ZynqPs extends BlackBox {
  val io = new Bundle {
    val fClk0 = out Bool()
    val fResetN0 = out Bool()
    val mAxiGp0AClk = in Bool()
    val mAxiGp0 = master(Axi4(ZynqPs.mAxiGpConfig))
  }

  setDefinitionName("zynqps_wrapper")
  io.fClk0.setName("FCLK0")
  io.fResetN0.setName("FRST0")
  io.mAxiGp0AClk.setName("M_AXI_GP0_ACLK")
  io.mAxiGp0.aw.ready.setName("M_AXI_GP0_awready")
  io.mAxiGp0.aw.valid.setName("M_AXI_GP0_awvalid")
  io.mAxiGp0.aw.addr.setName("M_AXI_GP0_awaddr")
  io.mAxiGp0.aw.id.setName("M_AXI_GP0_awid")
  io.mAxiGp0.aw.len.setName("M_AXI_GP0_awlen")
  io.mAxiGp0.aw.size.setName("M_AXI_GP0_awsize")
  io.mAxiGp0.aw.burst.setName("M_AXI_GP0_awburst")
  io.mAxiGp0.aw.lock.setName("M_AXI_GP0_awlock")
  io.mAxiGp0.aw.cache.setName("M_AXI_GP0_awcache")
  io.mAxiGp0.aw.qos.setName("M_AXI_GP0_awqos")
  io.mAxiGp0.aw.prot.setName("M_AXI_GP0_awprot")
  io.mAxiGp0.w.ready.setName("M_AXI_GP0_wready")
  io.mAxiGp0.w.valid.setName("M_AXI_GP0_wvalid")
  io.mAxiGp0.w.data.setName("M_AXI_GP0_wdata")
  io.mAxiGp0.w.strb.setName("M_AXI_GP0_wstrb")
  io.mAxiGp0.w.last.setName("M_AXI_GP0_wlast")
  io.mAxiGp0.b.ready.setName("M_AXI_GP0_bready")
  io.mAxiGp0.b.valid.setName("M_AXI_GP0_bvalid")
  io.mAxiGp0.b.id.setName("M_AXI_GP0_bid")
  io.mAxiGp0.b.resp.setName("M_AXI_GP0_bresp")
  io.mAxiGp0.ar.ready.setName("M_AXI_GP0_arready")
  io.mAxiGp0.ar.valid.setName("M_AXI_GP0_arvalid")
  io.mAxiGp0.ar.addr.setName("M_AXI_GP0_araddr")
  io.mAxiGp0.ar.id.setName("M_AXI_GP0_arid")
  io.mAxiGp0.ar.len.setName("M_AXI_GP0_arlen")
  io.mAxiGp0.ar.size.setName("M_AXI_GP0_arsize")
  io.mAxiGp0.ar.burst.setName("M_AXI_GP0_arburst")
  io.mAxiGp0.ar.lock.setName("M_AXI_GP0_arlock")
  io.mAxiGp0.ar.cache.setName("M_AXI_GP0_arcache")
  io.mAxiGp0.ar.qos.setName("M_AXI_GP0_arqos")
  io.mAxiGp0.ar.prot.setName("M_AXI_GP0_arprot")
  io.mAxiGp0.r.ready.setName("M_AXI_GP0_rready")
  io.mAxiGp0.r.valid.setName("M_AXI_GP0_rvalid")
  io.mAxiGp0.r.data.setName("M_AXI_GP0_rdata")
  io.mAxiGp0.r.id.setName("M_AXI_GP0_rid")
  io.mAxiGp0.r.resp.setName("M_AXI_GP0_rresp")
  io.mAxiGp0.r.last.setName("M_AXI_GP0_rlast")
}